### ISSUE TITLE
separation in location area encounters

### ISSUE THREAD

**Issue by zaneadix** [veekun/pokedex#156]
I'm sure this isn't an issue at all but I'm hoping to clear something up. I've been working quite a bit on V2 of [Pokeapi](https://github.com/phalt/pokeapi) which is making heavy use of the data here (which is fantastic).

I've been working on wrapping my head around encounters and how they relate to location areas and have noticed a "separation" in how they're stored in the db. For example in Cerulean Cave I've noticed multiple entries for the same area.
```
323,147,140,1f
324,147,141,2f
325,147,142,b1f
...
472,147,24,1f
473,147,25,2f
474,147,26,b1f
```
After digging deeper I've noticed the areas 323-325 relate to encounters in R, B, Y, HG, and SS and the areas 472-474 relate only to encounters in FR and LG.

Is there a clear reason for this separation? Is this just due to how the data has evolved over time? Why would they not all be grouped together? Am I reading too far into this? AM I LOSING MY MIND!? HALP!

**Comment by magical** [comment]
When eevee ripped R/B encounters, we decided to reuse the HG/SS location areas. This turned out not to be very useful from a presentation point of view since even where areas are shared, the encounters changed too much between Gen I and II to really show a useful diff.

Therefore when i ripped FR/LG encounters i gave them their own set of location_areas, arguing that since the areas are somewhat specific to each version group anyway, we should keep them separate in the database and let the ui handle matching up identically-named areas if it really wants too.

The other devs disagreed, so subsequent rips have reused location_areas. There's an open issue to fix FR/LG: https://github.com/veekun/pokedex/issues/103.

**Comment by zaneadix** [comment]
Ok cool, that makes sense. Thanks for the quick response @magical :) :+1:
