### ISSUE TITLE
No slot value in encounter_slots

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [veekun/pokedex#166]
In `encounter_slots.csv` there are no values in the `slot` column [for several lines](https://github.com/veekun/pokedex/blob/4e675e71437247861211a73660a79b2685d31c04/pokedex/data/csv/encounter_slots.csv#L111).

Is this an error, or is it intentional for a particular reason?

**Comment by antialiasis** [comment]
I happened to ask this question the other day and get an answer from magical, so:

These slots are R/B's Super Rod slots, which don't actually correspond to in-game slots, because they actually have a varying number of slots per location, with an equal chance of each. Thus, in one location there could be two 50% slots for the Super Rod, and in another there could be three 33.33% slots. Because the data structure here doesn't account for slots being able to have varying rarities or for slots to sometimes exist in a location and sometimes not, the slots in the database are "fake", designed simply to be able to accommodate R/B's data with the correct probabilities without having to design the whole data structure around this one edge case.

**Comment by FarbodSalamat-Zadeh** [comment]
Thanks for the answer @antialiasis - it makes more sense now :)
