### ISSUE TITLE
OR/AS egg moves are missing for non-standard forms.

### ISSUE THREAD

**Issue by jpirnat** [veekun/pokedex#219]
https://veekun.com/dex/pokemon/rattata?form=alola
https://veekun.com/dex/pokemon/sandshrew?form=alola
https://veekun.com/dex/pokemon/vulpix?form=alola
https://veekun.com/dex/pokemon/oricorio?form=pom-pom
https://veekun.com/dex/pokemon/oricorio?form=pau
etc.

I noticed this when Alolan Meowth wasn't in the search results for Pokémon who learn Parting Shot. I saw it didn't have any egg moves listed, checked other SM Pokémon and saw that in general they did have egg moves, checked other Alolan forms and saw that they also didn't have any, checked other alternate forms SM introduced and saw that in general they also didn't have any. Midnight Lycanroc currently has egg move data, though, so I don't know what the real pattern is. But whatever it is, this is a significant amount of missing data and I hope it's addressed soon!

**Comment by magical** [comment]
Yep. We're missing egg move for all non-default forms since OR/AS. There's a `FIXME` comment about this in the data ripper: https://github.com/veekun/pokedex/blob/yaml/pokedex/extract/oras.py#L1805

Here's another example: https://veekun.com/dex/pokemon/basculin?form=blue-striped#moves

Midnight Lycanroc isn't affected doesn't have any egg moves - Rockruff does. There weren't many examples of basic/baby pokemon with alt forms in breedable families before gen 7. Just Basculin and Pumpkaboo i think? Then S/M added Alolan forms and they got a lot more common.

**Comment by magical** [comment]
Ran into this yesterday when looking up egg moves for Alolan Vulpix. Fortunately it doesn't seem to be a schema problem, just a ripping problem. The data looks straightforward enough to rip if someone has the time to do it.

**Comment by magical** [comment]
S/M/US/UM egg moves are in! Re titling this issue to be about OR/AS.
