### ISSUE TITLE
Add Japanese Generation names

### ISSUE THREAD

**Issue by SethETaron** [veekun/pokedex#252]
Japanese generation names are missing from generation_names.csv

**Comment by SethETaron** [comment]
This probably isn't the appropriate place to ask this, but do you guys have a standard for the use of latin numerals in Japanese text? Generation I, for example, could be written 第1世代 or 第一世代. For a title like this, 第一世代 is definitely more common, so in this case, I would say it's better. Are these typically being handled on a case by case basis like this? Or is there some more general rule being applied to decide which one will be stored?

**Comment by SethETaron** [comment]
Added in PR #253

**Comment by magical** [comment]
> This probably isn't the appropriate place to ask this, but do you guys have a standard for the use of latin numerals in Japanese text? 

Most of the text is ripped from the games; i don't think we have any Japanese text that has been translated by hand. So the short answer is "no".

If you can find it in any official sources, go with what they use. Otherwise i'd use whatever spelling is more common in the fandom.

I will note that the games tend to use numerals -- eg ２番道路 (Route 2). Also, if we go with numerals they should probably be fullwidth -- 第１世代, not 第1世代 .

**Comment by SethETaron** [comment]
Thanks, all good information. I grew up in Japan and can speak/write at native level so I can probably help out with translations for fields that can't be ripped from games (such as the move learn methods). There is a really dedicated fandom for Pokemon in Japan, so looking on Japanese wikis or just using my own experience playing the games in Japanese will probably be enough to get by :) I will go ahead and use full width Arabic numerals whenever I find a place where Arabic numerals are more appropriate.

**Comment by magical** [comment]
Oh nice, i'll trust your judgement then.
