### ISSUE TITLE
Missing evolution data for Galar forms

### ISSUE THREAD

**Issue by magical** [veekun/pokedex#337]
Cursola should evolve from Corsola but it doesn't. There's no entry in pokemon_evolution, evolves_from_species_id is unset, and they have different evolution_chain_ids.

This seems to be true of all Galarian evolutions. (But not native Gen 8 pokemon, e.g. Milcrey -> Alcremie is fine)

@Parnassius

**Comment by Parnassius** [comment]
Huh, that's strange. I'll try to take a look

**Comment by Parnassius** [comment]
Ok, I missed every evolution from non-default forms. I fixed them [here](https://github.com/Parnassius/pokedex/commit/fea4c4166d20dcfe6c9826ee3ad8ce9088eaf492).

By dumping everything again I also found a couple missing evolution methods, mainly for alola forms. I'm not sure if I should keep them, since this would cause the site to show Ice Stone as an evolution method for Kantonian Vulpix => Kantonian Ninetales. There's also a `dusk` evolution method for Lycanroc Dusk, but it breaks a CHECK constraint on `pokemon_evolutions.pokemon_evolution_time_of_day`.

The other thing I'm unsure about is how to name runerigus's evolution method. Bulbapedia lists it as "It evolves from Galarian Yamask when the player travels under the stone bridge in Dusty Bowl after Yamask takes at least 49 HP in damage (even if healed) without fainting. Taking damage from certain sources does not contribute to the 49 HP damage requirement such as self inflicted curse damage or weather effects."

**Comment by magical** [comment]
>  I'm not sure if I should keep them, since this would cause the site to show Ice Stone as an evolution method for Kantonian Vulpix => Kantonian Ninetales (`pokemon_evolutions` doesn't have a `forme_id` column). 

I'd prefer to keep them. Yes, it's a bit confusing, but it's also confusing not to show them at all. Of course fixing the schema would be even better but. one thing at a time.

> There's also a `dusk` evolution method for Lycanroc Dusk, but it breaks a CHECK constraint on `pokemon_evolutions.pokemon_evolution_time_of_day`.

I added dusk: https://github.com/veekun/pokedex/commit/ffd472491bd918c36f53841394feff492ef627c2
 
> The other thing I'm unsure about is how to name runerigus's evolution method. Bulbapedia lists it as "It evolves from Galarian Yamask when the player travels under the stone bridge in Dusty Bowl after Yamask takes at least 49 HP in damage (even if healed) without fainting. Taking damage from certain sources does not contribute to the 49 HP damage requirement such as self inflicted curse damage or weather effects."

That's, uh... Wow. Just when you think they're starting to take it easy with the wacky evolution methods they hit you with this.

I'll probably summarize it as "Walk under the Dusty Bowl bridge after surviving 49 damage" on the site. But that goes [elsewhere](https://github.com/magical/spline-pokedex/blob/pyramid_pokedex/splinext/pokedex/templates/pokedex/lib.mako#L592).

If you want to keep it terse, like method 4 "Shed", then maybe "Take damage"? (Although strictly speaking the trigger is just "walk", and "take damage" is a condition. "Go somewhere after taking damage"? idk).

**Comment by Parnassius** [comment]
> I added dusk: [ffd4724](https://github.com/veekun/pokedex/commit/ffd472491bd918c36f53841394feff492ef627c2)

That's great, thanks!

> That's, uh... Wow. Just when you think they're starting to take it easy with the wacky evolution methods they hit you with this.
> 
> I'll probably summarize it as "Walk under the Dusty Bowl bridge after surviving 49 damage" on the site. But that goes [elsewhere](https://github.com/magical/spline-pokedex/blob/1997ae131ff7e5f355fb2cef59adc41f06c94613/splinext/pokedex/templates/pokedex/lib.mako#L592).
> 
> If you want to keep it terse, like method 4 "Shed", then maybe "Take damage"? (Although strictly speaking the trigger is just "walk", and "take damage" is a condition. "Go somewhere after taking damage"? idk).

I opted for `take-damage` as an identifier, and a slightly more descriptive `Go somewhere after taking damage` in the prose table.

**Comment by magical** [comment]
I guess we shouldn't feel too bad about missing these, because the official pokedex made the same mistake: https://github.com/PokeAPI/pokedex/issues/40#issue-842958271 😂
